# Configuration for data constrained scaling law discovery with OpenEvolve
max_iterations: 50
checkpoint_interval: 1
log_level: "INFO"
random_seed: 42

# LLM configuration
llm:
  primary_model: gpt-5
  primary_model_weight: 1.0
  secondary_model: gpt-5
  secondary_model_weight: 0.0
  api_base: "http://api.llm.wq/v1"
  max_tokens: 16384
  timeout: 240
  retries: 10
  retry_delay: 20

# Prompt configuration
prompt:
  system_message: |
    You are an expert in scaling laws and machine learning who specializes in discovering and improving scaling law functions for different LLM training scenarios. Your task is to evolve both the `scaling_law_func` function (currently a naive power law) and the `fit_scaling_law` optimization algorithm (currently a naive BFGS) to better model the relationship between training data characteristics and model loss (negative logprobs) under data-constrained conditions.

    **IMPORTANT: The scaling law function must use no more than 7 parameters.**

    Focus on mathematical accuracy across different data scales, cross-dataset generalization, parameter efficiency (simple forms that can be fitted with limited data), and numerical/theoretical stability.

    **DATA CHARACTERISTICS (16 total data points):**
    - Features: [params, tokens] - 2D input
    - Labels: loss - scalar output
    - Dataset size: 16
    - Parameter range (P): 1.4e7 to 6.6e10 (14M to 66B parameters)
    - Token count range (D): 3e11 or 1.8e11 tokens
    - Loss range: 1.0 to 7.0 (negative log of the probability)
    - Model architectures: Transformer variants with different parameterizations
    - Data explores scaling under token constraints

    The function signatures must remain:

    ```python
    def scaling_law_func(data_points, hyperparams):
        # data_points: (N,2) array with columns [params, tokens]
        # tokens: Array of token counts
        # params: Array of parameter counts
        # hyperparams: Array of up to 6 parameters
        # Returns: Predicted loss values

    def fit_scaling_law(data_points, loss_values):
        # data_points: (N,2) array with columns [params, tokens]
        # loss_values: Array of corresponding loss values
        # Returns: Optimized hyperparameters (up to 6 parameters)
    ```

    Write all improvements between # EVOLVE-BLOCK-START and # EVOLVE-BLOCK-END markers.

    You are not allowed to use input-dependent feature in scaling_law_func, e.g., median / min / max / etc.

  num_top_programs: 3
  num_diverse_programs: 2
  use_template_stochasticity: true

# Database configuration for evolution
database:
  population_size: 100
  archive_size: 50
  num_islands: 5
  migration_interval: 25
  migration_rate: 0.1
  elite_selection_ratio: 0.1
  exploration_ratio: 0.2
  exploitation_ratio: 0.7
  feature_dimensions: ["combined_score", "complexity", "diversity"]
  feature_bins: 10

# Evaluator configuration
evaluator:
  timeout: 600
  max_retries: 3
  cascade_evaluation: false
  cascade_thresholds: [0.3, 0.6]
  parallel_evaluations: 4
  use_llm_feedback: false

# Evolution settings
diff_based_evolution: false
max_code_length: 100000